---------------------------PART A-------------------------------------------
-- Create the Products table
CREATE TABLE Products (
 Product_id INT PRIMARY KEY,
 Product_Name VARCHAR(250) NOT NULL,
 Price DECIMAL(10, 2) NOT NULL
);

-- Insert data into the Products table
INSERT INTO Products (Product_id, Product_Name, Price) VALUES
(1, 'Smartphone', 35000),
(2, 'Laptop', 65000),
(3, 'Headphones', 5500),
(4, 'Television', 85000),
(5, 'Gaming Console', 32000);

SELECT * FROM Products

--1. Create a cursor Product_Cursor to fetch all the rows from a products table.
DECLARE @PRODUCT_ID INT
DECLARE @PRODUCT_NAME VARCHAR(50)
DECLARE @PRICE DECIMAL(10,2)

DECLARE PRODUCT_CURSOR CURSOR
FOR
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE
FROM Products

OPEN PRODUCT_CURSOR
FETCH NEXT FROM PRODUCT_CURSOR INTO
@PRODUCT_ID,@PRODUCT_NAME,@PRICE

WHILE @@FETCH_STATUS=0
BEGIN
	PRINT CAST(@PRODUCT_ID AS VARCHAR)+'-'+@PRODUCT_NAME+'-'+CAST(@PRICE AS VARCHAR)
	FETCH NEXT FROM PRODUCT_CURSOR INTO
	@PRODUCT_ID,@PRODUCT_NAME,@PRICE
END

CLOSE PRODUCT_CURSOR
DEALLOCATE PRODUCT_CURSOR

--2. Create a cursor Product_Cursor_Fetch to fetch the records in form of ProductID_ProductName.(Example: 1_Smartphone)
DECLARE @PRODUCTID INT
DECLARE @PRODUCTNAME VARCHAR(50)

DECLARE PRODUCT_CURSOR_FETCH CURSOR
FOR
SELECT PRODUCT_ID,PRODUCT_NAME
FROM Products

OPEN PRODUCT_CURSOR_FETCH
FETCH NEXT FROM PRODUCT_CURSOR_FETCH INTO
@PRODUCTID,@PRODUCTNAME

WHILE @@FETCH_STATUS=0
BEGIN
	PRINT CAST(@PRODUCTID AS VARCHAR)+'_'+@PRODUCTNAME
	FETCH NEXT FROM PRODUCT_CURSOR_FETCH INTO
	@PRODUCTID,@PRODUCTNAME
END

CLOSE PRODUCT_CURSOR_FETCH
DEALLOCATE PRODUCT_CURSOR_FETCH

--3. Create a Cursor to Find and Display Products Above Price 30,000
DECLARE @PRODUCTNAME VARCHAR(50)
DECLARE @PRICE DECIMAL(10,2)

DECLARE PRODUCT_CURSOR_PRICE CURSOR
FOR
SELECT PRODUCT_NAME,PRICE
FROM Products
WHERE Price>30000

OPEN PRODUCT_CURSOR_PRICE
FETCH NEXT FROM PRODUCT_CURSOR_PRICE INTO
@PRODUCTNAME,@PRICE

WHILE @@FETCH_STATUS=0
BEGIN
	IF @PRICE>30000
	PRINT @PRODUCTNAME+'_'+CAST(@PRICE AS VARCHAR)
	FETCH NEXT FROM PRODUCT_CURSOR_PRICE INTO
	@PRODUCTNAME,@PRICE
END

CLOSE PRODUCT_CURSOR_PRICE
DEALLOCATE PRODUCT_CURSOR_PRICE

--4. Create a cursor Product_CursorDelete that deletes all the data from the Products table.
DECLARE @PRODUCT_ID INT

DECLARE PRODUCT_CURSOR_DELETE CURSOR
FOR
SELECT PRODUCT_ID
FROM PRODUCTS

OPEN PRODUCT_CURSOR_DELETE
FETCH NEXT FROM PRODUCT_CURSOR_DELETE INTO
@PRODUCT_ID

WHILE @@FETCH_STATUS=0
BEGIN
	DELETE FROM Products
	WHERE Product_id = @PRODUCT_ID
	FETCH NEXT FROM PRODUCT_CURSOR_DELETE INTO
	@PRODUCT_ID
END

CLOSE PRODUCT_CURSOR_DELETE
DEALLOCATE PRODUCT_CURSOR_DELETE

------------------------------------------------PART B-------------------------------------------------
--5. Create a cursor Product_CursorUpdate that retrieves all the data from the products table and increases the price by 10%
DECLARE @PRODUCT_ID INT
DECLARE @PRODUCT_NAME VARCHAR(50)
DECLARE @PRICE DECIMAL(10,2)

DECLARE PRODUCT_CURSORUPDATE CURSOR
FOR
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE
FROM Products

OPEN PRODUCT_CURSORUPDATE
FETCH NEXT FROM PRODUCT_CURSORUPDATE INTO
@PRODUCT_ID,@PRODUCT_NAME,@PRICE

WHILE @@FETCH_STATUS=0
BEGIN
	UPDATE Products
	SET Price = Price+Price*0.1
	WHERE Product_id = @PRODUCT_ID
	PRINT CAST(@PRODUCT_ID AS VARCHAR)+'-'+@PRODUCT_NAME+'-'+CAST(@PRICE AS VARCHAR)
	FETCH NEXT FROM PRODUCT_CURSORUPDATE INTO
	@PRODUCT_ID,@PRODUCT_NAME,@PRICE
END

CLOSE PRODUCT_CURSORUPDATE
DEALLOCATE PRODUCT_CURSORUPDATE

SELECT * FROM PRODUCTS

--6. Create a Cursor to Rounds the price of each product to the nearest whole number.
DECLARE @PRODUCT_ID INT
DECLARE @PRODUCT_NAME VARCHAR(50)
DECLARE @PRICE DECIMAL(10,2)

DECLARE PRODUCT_CURSORROUNDOFF CURSOR
FOR
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE
FROM Products

OPEN PRODUCT_CURSORROUNDOFF
FETCH NEXT FROM PRODUCT_CURSORROUNDOFF INTO
@PRODUCT_ID,@PRODUCT_NAME,@PRICE

WHILE @@FETCH_STATUS=0
BEGIN
	UPDATE Products
	SET Price = ROUND(PRICE,0)
	WHERE Product_id = @PRODUCT_ID
	PRINT CAST(@PRODUCT_ID AS VARCHAR)+'-'+@PRODUCT_NAME+'-'+CAST(@PRICE AS VARCHAR)
	FETCH NEXT FROM PRODUCT_CURSORROUNDOFF INTO
	@PRODUCT_ID,@PRODUCT_NAME,@PRICE
END

CLOSE PRODUCT_CURSORROUNDOFF
DEALLOCATE PRODUCT_CURSORROUNDOFF

------------------------------------------------PART C----------------------------------------------------------
--7. Create a cursor to insert details of Products into the NewProducts table if the product is “Laptop” (Note: Create NewProducts table first with same fields as Products table)
CREATE TABLE NEWPRODUCTS (
 Product_id INT PRIMARY KEY,
 Product_Name VARCHAR(250) NOT NULL,
 Price DECIMAL(10, 2) NOT NULL
);

DECLARE @PRODUCT_ID INT
DECLARE @PRODUCT_NAME VARCHAR(50)
DECLARE @PRICE DECIMAL(10,2)

DECLARE PRODUCT_CURSORINSERT CURSOR
FOR
SELECT PRODUCT_ID,PRODUCT_NAME,PRICE
FROM Products
WHERE Product_Name = 'Laptop'

OPEN PRODUCT_CURSORINSERT
FETCH NEXT FROM PRODUCT_CURSORINSERT INTO
@PRODUCT_ID,@PRODUCT_NAME,@PRICE

WHILE @@FETCH_STATUS=0
BEGIN
	IF @PRODUCT_NAME='Laptop'
	INSERT INTO NEWPRODUCTS VALUES(@PRODUCT_ID,@PRODUCT_NAME,@PRICE)
	PRINT CAST(@PRODUCT_ID AS VARCHAR)+'-'+@PRODUCT_NAME+'-'+CAST(@PRICE AS VARCHAR)
	FETCH NEXT FROM PRODUCT_CURSORINSERT INTO
	@PRODUCT_ID,@PRODUCT_NAME,@PRICE
END

CLOSE PRODUCT_CURSORINSERT
DEALLOCATE PRODUCT_CURSORINSERT

--8. Create a Cursor to Archive High-Price Products in a New Table (ArchivedProducts), Moves products with a price above 50000 to an archive table, removing them from the original Products table.
CREATE TABLE ARCHIVEDPRODUCTS (
 Product_id INT PRIMARY KEY,
 Product_Name VARCHAR(250) NOT NULL,
 Price DECIMAL(10, 2) NOT NULL
);

DECLARE @PRODUCT_ID INT
DECLARE @PRODUCT_NAME VARCHAR(50)
DECLARE @PRICE DECIMAL(10,2)


DECLARE Product_CursorArchive CURSOR FOR
SELECT Product_id, Product_Name, Price
FROM Products
WHERE Price > 50000;

OPEN Product_CursorArchive;
FETCH NEXT FROM Product_CursorArchive INTO @Product_id, @Product_Name, @Price;

WHILE @@FETCH_STATUS = 0
BEGIN
    -- Insert into ArchivedProducts and remove from Products
    INSERT INTO ArchivedProducts (Product_id, Product_Name, Price)
    VALUES (@Product_id, @Product_Name, @Price);
    
    DELETE FROM Products WHERE Product_id = @Product_id;

    FETCH NEXT FROM Product_CursorArchive INTO @Product_id, @Product_Name, @Price;
END

CLOSE Product_CursorArchive;
DEALLOCATE Product_CursorArchive;

SELECT * FROM ARCHIVEDPRODUCTS 