-- Creating PersonInfo Table
CREATE TABLE PersonInfo (
 PersonID INT PRIMARY KEY,
 PersonName VARCHAR(100) NOT NULL,
 Salary DECIMAL(8,2) NOT NULL,
 JoiningDate DATETIME NULL,
 City VARCHAR(100) NOT NULL,
 Age INT NULL,
 BirthDate DATETIME NOT NULL
);
-- Creating PersonLog Table
CREATE TABLE PersonLog (
 PLogID INT PRIMARY KEY IDENTITY(1,1),
 PersonID INT NOT NULL,
 PersonName VARCHAR(250) NOT NULL,
 Operation VARCHAR(50) NOT NULL,
 UpdateDate DATETIME NOT NULL,
);

DROP TABLE PersonInfo
DROP TABLE PersonLog


------------------------------------PART-A--------------------------------------------
--1. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo table to display a message “Record is Affected.”
CREATE TRIGGER TR_INSERT_UPDATE_DELETE
ON PERSONINFO
AFTER INSERT,UPDATE,DELETE
AS
BEGIN
	PRINT 'RECORD IS AFFECTED'
END

INSERT INTO PERSONINFO VALUES(101,'ABC',12000,'2020-01-13','RAJKOT',52,'1996-01-15')\
DROP TRIGGER TR_INSERT_UPDATE_DELETE

--2. Create a trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo table. For that, log all operations performed on the person table into PersonLog
CREATE TRIGGER TR_PERSON_INSERT
ON PERSONINFO
AFTER INSERT
AS
BEGIN
	DECLARE @PERSONID INT,@PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM inserted
	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'INSERT',GETDATE())
END

DROP TRIGGER TR_PERSON_INSERT

CREATE TRIGGER TR_PERSON_UPDATE
ON PERSONINFO
AFTER UPDATE
AS
BEGIN
	DECLARE @PERSONID INT,@PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM inserted
	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'UPDATE',GETDATE())
END

DROP TRIGGER TR_PERSON_UPDATE

CREATE TRIGGER TR_PERSON_DELETE
ON PERSONINFO
AFTER DELETE
AS
BEGIN
	DECLARE @PERSONID INT,@PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM deleted
	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'DELETE',GETDATE())
END

DROP TRIGGER TR_PERSON_DELETE

--3. Create an INSTEAD OF trigger that fires on INSERT, UPDATE and DELETE operation on the PersonInfo table. For that, log all operations performed on the person table into PersonLog.
CREATE TRIGGER TR_INSTEADOF_INSERT
ON PERSONINFO
INSTEAD OF INSERT
AS
BEGIN
	DECLARE @PERSONID INT,@PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM inserted

	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'INSERT',GETDATE())
END

DROP TRIGGER TR_INSTEADOF_INSERT

CREATE TRIGGER TR_INSTEADOF_UPDATE
ON PERSONINFO
INSTEAD OF UPDATE
AS
BEGIN
	DECLARE @PERSONID INT,@PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM inserted

	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'UPDATE',GETDATE())
END

DROP TRIGGER TR_INSTEADOF_UPDATE

CREATE TRIGGER TR_INSTEADOF_DELETE
ON PERSONINFO
INSTEAD OF DELETE
AS
BEGIN
	DECLARE @PERSONID INT,@PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM deleted

	INSERT INTO PERSONLOG VALUES(@PERSONID,@PERSONNAME,'DELETE',GETDATE())
END

DROP TRIGGER TR_INSTEADOF_DELETE

--4. Create a trigger that fires on INSERT operation on the PersonInfo table to convert person name into uppercase whenever the record is inserted.
CREATE TRIGGER TR_INSERT_PERSONINFO
ON PERSONINFO
AFTER INSERT
AS
BEGIN
	DECLARE @PERSONID INT,@PERSONNAME VARCHAR(50)
	SELECT @PERSONID=PERSONID,@PERSONNAME=PERSONNAME FROM inserted

	UPDATE PERSONINFO
	SET PERSONNAME = UPPER(@PERSONNAME)
	WHERE PERSONID = @PERSONID
END

DROP TRIGGER TR_INSERT_PERSONINFO

--5. Create trigger that prevent duplicate entries of person name on PersonInfo table.
CREATE OR ALTER TRIGGER tr_PreventDuplicateName
ON PersonInfo
INSTEAD OF INSERT
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM PersonInfo
        WHERE PersonName IN (SELECT PersonName FROM inserted)
    )
    BEGIN
        RAISERROR ('Duplicate PersonName is not allowed.', 16, 1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        INSERT INTO PersonInfo (PersonID, PersonName, Salary, JoiningDate, City, Age, BirthDate)
        SELECT PersonID, PersonName, Salary, JoiningDate, City, Age, BirthDate
        FROM inserted;
    END
END;

----6. Create trigger that prevent Age below 18 years.
CREATE OR ALTER TRIGGER tr_PreventUnderage
ON PersonInfo
AFTER INSERT
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted
        WHERE Age < 18
    )
    BEGIN
        RAISERROR ('Age must be 18 or older.', 16, 1);
        ROLLBACK TRANSACTION;
    END
    ELSE
    BEGIN
        INSERT INTO PersonInfo (PersonID, PersonName, Salary, JoiningDate, City, Age, BirthDate)
        SELECT PersonID, PersonName, Salary, JoiningDate, City, Age, BirthDate
        FROM inserted;
    END
END;

