CREATE DATABASE CSE_4A_167

---------------------------------PART A------------------------------------
-- Create Department Table
CREATE TABLE Department (
 DepartmentID INT PRIMARY KEY,
 DepartmentName VARCHAR(100) NOT NULL UNIQUE
);
-- Create Designation Table
CREATE TABLE Designation (
 DesignationID INT PRIMARY KEY,
 DesignationName VARCHAR(100) NOT NULL UNIQUE
);
-- Create Person Table
CREATE TABLE Person (
 PersonID INT PRIMARY KEY IDENTITY(101,1),
 FirstName VARCHAR(100) NOT NULL,
 LastName VARCHAR(100) NOT NULL,
 Salary DECIMAL(8, 2) NOT NULL,
 JoiningDate DATETIME NOT NULL,
 DepartmentID INT NULL,
 DesignationID INT NULL,
 FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID),
 FOREIGN KEY (DesignationID) REFERENCES Designation(DesignationID)
);

----------------------PART-A----------------------------------------------
--Department, Designation & Person Table’s INSERT, UPDATE & DELETE Procedures.
CREATE PROCEDURE PR_DEPARTMENT_INSERT
	@DEPARTMENTID INT,
	@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
	INSERT INTO DEPARTMENT
	(DEPARTMENTID,DEPARTMENTNAME)
	VALUES(@DEPARTMENTID,@DEPARTMENTNAME)
END

EXEC PR_DEPARTMENT_INSERT 1,'Admin'
EXEC PR_DEPARTMENT_INSERT 2,'IT'
EXEC PR_DEPARTMENT_INSERT 3,'HR' 
EXEC PR_DEPARTMENT_INSERT 4,'Account'

CREATE PROCEDURE PR_DESIGNATION_INSERT
	@DESIGNATIONID INT,
	@DESIGNATIONNAME VARCHAR(100)
AS
BEGIN
	INSERT INTO DESIGNATION
	(DESIGNATIONID,DESIGNATIONNAME)
	VALUES(@DESIGNATIONID,@DESIGNATIONNAME)
END

EXEC PR_DESIGNATION_INSERT 11 ,'Jobber'
EXEC PR_DESIGNATION_INSERT 12,'Welder'
EXEC PR_DESIGNATION_INSERT 13 ,'Clerk' 
EXEC PR_DESIGNATION_INSERT 14,'Manager'
EXEC PR_DESIGNATION_INSERT 15,'CEO'

CREATE PROCEDURE PR_PERSON_INSERT
	@FIRSTNAME VARCHAR(100),
	@LASTNAME VARCHAR(100),
	@SALARY DECIMAL(8,2),
	@JOININGDATE DATETIME,
	@DEPARTMENTID INT,
	@DESIGNATIONID INT
AS
BEGIN
	INSERT INTO PERSON
	(FIRSTNAME,LASTNAME,SALARY,JOININGDATE,DEPARTMENTID,DESIGNATIONID)
	VALUES(@FIRSTNAME,@LASTNAME,@SALARY,@JOININGDATE,@DEPARTMENTID,@DESIGNATIONID)
END

EXEC PR_PERSON_INSERT 'Rahul','Anshu',56000,'1990-01-01',1,12
EXEC PR_PERSON_INSERT 'Hardik','Hinsu',18000,'1990-09-25',2,11
EXEC PR_PERSON_INSERT 'Bhavin','Kamani',25000,'1991-05-14',NULL,11
EXEC PR_PERSON_INSERT 'Bhoomi','Patel',39000,'2014-02-20',1,13
EXEC PR_PERSON_INSERT 'Rohit','Rajgor',17000,'1990-07-23',2,15
EXEC PR_PERSON_INSERT 'Priya','Mehta',25000,'1990-10-18',2,NULL
EXEC PR_PERSON_INSERT 'Neha','Trivedi',18000,'2014-02-20',3,15

SELECT * FROM DEPARTMENT
SELECT * FROM DESIGNATION
SELECT * FROM PERSON

CREATE PROCEDURE PR_DEPARTMENT_UPDATE
	@DEPARTMENTID INT,
	@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
	UPDATE DEPARTMENT
	SET DEPARTMENTNAME=@DEPARTMENTNAME
	WHERE DEPARTMENTID=@DEPARTMENTID
END

CREATE PROCEDURE PR_DESIGNATION_UPDATE
	@DESIGNATIONID INT,
	@DESIGNATIONNAME VARCHAR(100)
AS
BEGIN
	UPDATE DESIGNATION
	SET DESIGNATIONNAME=@DESIGNATIONNAME
	WHERE DESIGNATIONID=@DESIGNATIONID
END

CREATE PROCEDURE PR_PERSON_UPDATE
	@PERSONID INT,
	@FIRSTNAME VARCHAR(100),
	@LASTNAME VARCHAR(100),
	@SALARY DECIMAL(8,2),
	@JOININGDATE DATETIME,
	@DEPARTMENTID INT,
	@DESIGNATIONID INT
AS
BEGIN
	UPDATE PERSON
	SET FIRSTNAME = @FIRSTNAME
	WHERE PERSONID = @PERSONID
END

CREATE OR ALTER PROC PR_DEPARTMENT_DELETE
	@DEPARTMENTID INT
AS
BEGIN
	DELETE FROM DEPARTMENT
	WHERE DEPARTMENTID = @DEPARTMENTID
END

CREATE OR ALTER PROC PR_DESIGNATION_DELETE
	@DESIGNATIONID INT
AS
BEGIN
	DELETE FROM DESIGNATION
	WHERE DESIGNATONID = @DESIGNATIONID
END

CREATE OR ALTER PROC PR_PERSON_DELETE
	@PERSONID INT
AS
BEGIN
	DELETE FROM PERSON
	WHERE PERSONID = @PERSONID
END

--2. Department, Designation & Person Table’s SELECTBYPRIMARYKEY
CREATE OR ALTER PROC PR_DEPARTMENT_SELECTBYPRIMARYKEY
	@DEPARTMENTID INT
AS
BEGIN
	SELECT * FROM DEPARTMENT
	WHERE DEPARTMENTID = @DEPARTMENTID
END

CREATE OR ALTER PROC PR_DESIGNATION_SELECTBYPRIMARYKEY
	@DESIGNATIONID INT
AS
BEGIN
	SELECT * FROM DESIGNATION
	WHERE DESIGNATIONID = @DESIGNATIONID
END

CREATE OR ALTER PROC PR_PERSON_SELECTBYPRIMARYKEY
	@PERSONID INT
AS
BEGIN
	SELECT * FROM PERSON
	WHERE PERSONID = @PERSONID
END

--3. Department, Designation & Person Table’s (If foreign key is available then do write join and take columns on select list)
CREATE OR ALTER PROC PR_THREETABLE_JOIN
AS
BEGIN
	SELECT * FROM PERSON INNER JOIN Department
	ON Person.DepartmentID = Department.DepartmentID
	INNER JOIN Designation
	ON Person.DesignationID = Designation.DesignationID
END

EXEC PR_THREETABLE_JOIN

--4. Create a Procedure that shows details of the first 3 persons.
CREATE OR ALTER PROC PR_PERSON_SELECT
AS
BEGIN
	SELECT TOP 3 * FROM PERSON INNER JOIN Department
	ON Person.DepartmentID = Department.DepartmentID
	INNER JOIN Designation
	ON Person.DesignationID = Designation.DesignationID
END

EXEC PR_PERSON_SELECT