CREATE DATABASE PAPAER_5

-- CREATE CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMERID INT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(50) NOT NULL,
    JOINDATE DATE NOT NULL
);

-- CREATE PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCTID INT PRIMARY KEY IDENTITY(1,1),
    PRODUCTNAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50),
    PRICE DECIMAL(10,2) NOT NULL,
    STOCKQUANTITY INT NOT NULL
);

-- CREATE ORDERS TABLE
CREATE TABLE ORDERS (
    ORDERID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMERS(CUSTOMERID),
    PRODUCTID INT FOREIGN KEY REFERENCES PRODUCTS(PRODUCTID),
    ORDERDATE DATE NOT NULL,
    QUANTITY INT NOT NULL,
    TOTALORDERAMOUNT DECIMAL(10,2) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL, -- PRICE AT THE TIME OF SALE
    ORDERSTATUS VARCHAR(20) CHECK (ORDERSTATUS IN ('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
);

-- INSERT SAMPLE CUSTOMERS
INSERT INTO CUSTOMERS (NAME, JOINDATE) VALUES
('ALICE SMITH', '2023-01-15'),
('BOB JOHNSON', '2023-02-20'),
('CHARLIE BROWN', '2023-03-05'),
('DAVID LEE', '2023-04-10'),
('EVE DAVIS', '2023-05-12');

-- INSERT SAMPLE PRODUCTS
INSERT INTO PRODUCTS (PRODUCTNAME, CATEGORY, PRICE, STOCKQUANTITY) VALUES
('16" LAPTOP', 'COMPUTER', 1200.00, 10),
('WIRELESS MOUSE', 'COMPUTER', 25.00, 50),
('IPHONE 15', 'MOBILE', 999.00, 20),
('GALAXY S24', 'MOBILE', 899.00, 30),
('MECHANICAL KEYBOARD', 'COMPUTER', 75.00, 5),  -- LOW STOCK
('4K MONITOR', 'COMPUTER', 450.00, 15),
('DESK LAMP', 'HOME', 45.00, 100);             -- NEVER ORDERED

-- INSERT SAMPLE ORDERS
INSERT INTO ORDERS (CUSTOMERID, PRODUCTID, ORDERDATE, QUANTITY, PRICE, TOTALORDERAMOUNT, ORDERSTATUS) VALUES
-- HIGH-VALUE ORDERS
(4, 3, '2024-10-01', 3, 999.00, 2997.00, 'PENDING'),   -- DAVID, IPHONE 15
(2, 3, '2024-05-11', 2, 999.00, 1998.00, 'SHIPPED'),    -- BOB, IPHONE 15
(1, 1, '2024-05-10', 1, 1200.00, 1200.00, 'DELIVERED'), -- ALICE, LAPTOP
(2, 1, '2024-07-15', 1, 1200.00, 1200.00, 'DELIVERED'), -- BOB, LAPTOP

-- REPEAT BUYERS (ALICE ON IPHONE, EVE ON KEYBOARD)
(1, 3, '2024-10-05', 1, 999.00, 999.00, 'DELIVERED'),  -- ALICE, IPHONE 15
(1, 3, '2024-10-10', 1, 999.00, 999.00, 'DELIVERED'),  -- ALICE, IPHONE 15 (REPEAT)

-- STOCK < PENDING QUERY (KEYBOARD: STOCK 5, PENDING 3+4=7)
(5, 5, '2024-11-15', 3, 75.00, 225.00, 'PENDING'),    -- EVE, KEYBOARD
(5, 5, '2024-11-16', 4, 75.00, 300.00, 'PENDING'),    -- EVE, KEYBOARD (REPEAT)

-- CANCELLED ORDER BEFORE 2024
(2, 2, '2023-12-20', 1, 25.00, 25.00, 'CANCELLED'),   -- BOB, MOUSE

-- OTHER ORDERS
(1, 2, '2024-05-10', 1, 25.00, 25.00, 'DELIVERED'),    -- ALICE, MOUSE
(3, 4, '2024-06-01', 1, 899.00, 899.00, 'DELIVERED');  -- CHARLIE, GALAXY S24


--QUESTION 1: LIST TOP 5 HIGHEST AMOUNT ORDERS WITH CUSTOMER NAME & PRODUCT NAME. [CITE: 310]
SELECT TOP 5 CUSTOMERS.NAME,PRODUCTS.PRODUCTNAME,ORDERS.TOTALORDERAMOUNT
FROM CUSTOMERS INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
INNER JOIN PRODUCTS
ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
ORDER BY ORDERS.TOTALORDERAMOUNT DESC

--QUESTION 2: LIST PRODUCTS WITH CATEGORY WHICH ARE NEVER ORDERED. [CITE: 311]
SELECT PRODUCTS.PRODUCTNAME,PRODUCTS.CATEGORY
FROM PRODUCTS LEFT JOIN ORDERS
ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
WHERE ORDERS.PRODUCTID IS NULL

--QUESTION 3: LIST CATEGORY WISE TOTAL ORDERS, TOTAL ORDERED QUANTITY AND TOTAL ORDER AMOUNT. [CITE: 312]
SELECT PRODUCTS.CATEGORY,COUNT(ORDERS.ORDERID) AS TOTALORDERS,SUM(ORDERS.QUANTITY) AS QUANTITY,
SUM(ORDERS.TOTALORDERAMOUNT) AS TOTALORDERAMOUNT 
FROM PRODUCTS INNER JOIN ORDERS
ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
GROUP BY PRODUCTS.CATEGORY

--QUESTION 4: LIST PRODUCTS WITH AVERAGE PRICE OF "COMPUTER" CATEGORY. [CITE: 313]
SELECT PRODUCTNAME,PRICE
FROM PRODUCTS
WHERE PRICE > (
	SELECT AVG(PRICE) FROM PRODUCTS WHERE CATEGORY = 'COMPUTER'
);

--QUESTION 5: FIND CUSTOMERS WHO ORDERED THE SAME PRODUCT MORE THAN ONCE. (REPEAT BUYERS) [CITE: 316, 317]
SELECT CUSTOMERS.NAME,PRODUCTS.PRODUCTNAME
FROM CUSTOMERS INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
INNER JOIN PRODUCTS
ON  PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
GROUP BY CUSTOMERS.NAME,PRODUCTS.PRODUCTNAME
HAVING COUNT(ORDERS.ORDERID) > 1

--QUESTION 6: WHICH PRODUCT IS HIGHEST SELLING IN TERMS OF QUANTITY? [CITE: 318]
SELECT TOP 1 WITH TIES PRODUCTS.PRODUCTNAME,SUM(ORDERS.QUANTITY) AS TOTALQUANTITYSOLD
FROM PRODUCTS INNER JOIN ORDERS
ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
GROUP BY PRODUCTS.PRODUCTNAME
ORDER BY SUM(ORDERS.QUANTITY) DESC

--QUESTION 7: DELETE THOSE ORDERS WHICH ARE CANCELLED AND PLACED BEFORE '2024-01-01'. [CITE: 320]
DELETE FROM ORDERS
WHERE ORDERSTATUS = 'CANCELLED' AND ORDERDATE < '2024-01-01' 

--QUESTION 8: LIST PRODUCTS WHOSE CURRENT STOCK IS LESS THAN CURRENT PENDING ORDERS. [CITE: 321]
SELECT PRODUCTS.PRODUCTNAME,PRODUCTS.STOCKQUANTITY,SUM(ORDERS.QUANTITY) AS PENDINGQUANTITY
FROM PRODUCTS INNER JOIN ORDERS
ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
WHERE ORDERS.ORDERSTATUS = 'PENDING'
GROUP BY PRODUCTS.PRODUCTNAME,PRODUCTS.STOCKQUANTITY
HAVING SUM(ORDERS.QUANTITY) > PRODUCTS.STOCKQUANTITY

--Question 9: List Top 10 Customers with highest total order amount of Category "Mobile". [cite: 322]
SELECT TOP 10 CUSTOMERS.NAME,SUM(ORDERS.TOTALORDERAMOUNT) AS HIGHESTTOTALAMOUNT
FROM CUSTOMERS INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.CUSTOMERID
INNER JOIN PRODUCTS
ON PRODUCTS.PRODUCTID = ORDERS.PRODUCTID
WHERE PRODUCTS.CATEGORY = 'MOBILE'
GROUP BY CUSTOMERS.NAME
ORDER BY SUM(ORDERS.TOTALORDERAMOUNT) DESC

--Question 10: List Date wise Total Order Amount. [cite: 324]
SELECT ORDERDATE,SUM(TOTALORDERAMOUNT) AS TOTALAMOUNT
FROM ORDERS
GROUP BY ORDERDATE
ORDER BY ORDERDATE